// Generated by `wit-bindgen` 0.9.0. DO NOT EDIT!
#ifndef __BINDINGS_CRITTER_H
#define __BINDINGS_CRITTER_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>

typedef struct {
  char*ptr;
  size_t len;
} critter_string_t;

// Exported Functions from `component:example/greeting`
void exports_component_example_greeting_hello(critter_string_t *greeting, critter_string_t *ret);

// Helper Functions

void critter_string_set(critter_string_t *ret, const char*s);
void critter_string_dup(critter_string_t *ret, const char*s);
void critter_string_free(critter_string_t *ret);

#ifdef __cplusplus
}
#endif
#endif
