// Generated by `wit-bindgen` 0.9.0. DO NOT EDIT!
#include "power.h"


__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

// Component Adapters

__attribute__((__export_name__("component:example/control#volt-var-ctrl")))
double __wasm_export_exports_component_example_control_volt_var_ctrl(double arg, double arg0, double arg1, double arg2, double arg3, double arg4, double arg5, double arg6, double arg7) {
  double ret = exports_component_example_control_volt_var_ctrl(arg, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
  return ret;
}

extern void __component_type_object_force_link_power(void);
void __component_type_object_force_link_power_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_power();
}
