// Generated by `wit-bindgen` 0.9.0. DO NOT EDIT!
#ifndef __BINDINGS_POWER_H
#define __BINDINGS_POWER_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>

// Exported Functions from `component:example/control`
double exports_component_example_control_volt_var_ctrl(double setp, double alpha, double gamma, double delta, double vavg, double kv, double cap, double dert, double qprev);

#ifdef __cplusplus
}
#endif
#endif
